//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRaoVat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbtributeAndValue
    {
        public int id { get; set; }
        public string value { get; set; }
        public int post_id { get; set; }
        public int atribute_id { get; set; }
    
        public virtual Atribute Atribute { get; set; }
        public virtual Post Post { get; set; }
    }
}
