//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRaoVat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoaPhatThanhEntities : DbContext
    {
        public LoaPhatThanhEntities()
            : base("name=LoaPhatThanhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbtributeAndValue> AbtributeAndValues { get; set; }
        public virtual DbSet<Atribute> Atributes { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<BrandSelect> BrandSelects { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Dealed> Dealeds { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Favorite> Favorites { get; set; }
        public virtual DbSet<Follow> Follows { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<RateUser> RateUsers { get; set; }
        public virtual DbSet<SeccondCategory> SeccondCategories { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThirdCategory> ThirdCategories { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Ward> Wards { get; set; }
    }
}
