//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRaoVat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealed
    {
        public int deal_id { get; set; }
        public System.DateTime deal_date { get; set; }
        public bool is_delivering { get; set; }
        public bool is_dealed { get; set; }
        public bool is_pending { get; set; }
        public int post_id { get; set; }
        public string user_id { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
