//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRaoVat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int notification_id { get; set; }
        public Nullable<int> post_id { get; set; }
        public System.DateTime time { get; set; }
        public string value { get; set; }
        public bool request_delivery { get; set; }
        public bool follow_action { get; set; }
        public Nullable<bool> post_action { get; set; }
        public string user_id { get; set; }
        public string reciever { get; set; }
        public bool is_read { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
