//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRaoVat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.AbtributeAndValues = new HashSet<AbtributeAndValue>();
            this.Dealeds = new HashSet<Dealed>();
            this.Favorites = new HashSet<Favorite>();
            this.Images = new HashSet<Image>();
            this.Notifications = new HashSet<Notification>();
        }
        public int post_id { get; set; }
        public string user_id { get; set; }
        public int ward_id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public System.DateTime date_posted { get; set; }
        [Required(ErrorMessage = "You must input price!")]
        [Display(Name = "Price")]
        [DisplayFormat(DataFormatString = "{0:0,0}")]

        public double price { get; set; }
        public bool is_hided { get; set; }
        public bool is_approved { get; set; }
        public bool is_seller { get; set; }
        public int category_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public int seccond_cate_id { get; set; }
        public Nullable<int> third_cate_id { get; set; }
        [NotMapped]
        public string hinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbtributeAndValue> AbtributeAndValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dealed> Dealeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual Product Product { get; set; }
        public virtual SeccondCategory SeccondCategory { get; set; }
        public virtual ThirdCategory ThirdCategory { get; set; }
        public virtual User User { get; set; }
        public virtual Ward Ward { get; set; }
    }
}
