//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRaoVat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Dealeds = new HashSet<Dealed>();
            this.Favorites = new HashSet<Favorite>();
            this.Follows = new HashSet<Follow>();
            this.Follows1 = new HashSet<Follow>();
            this.Notifications = new HashSet<Notification>();
            this.Notifications1 = new HashSet<Notification>();
            this.Posts = new HashSet<Post>();
            this.RateUsers = new HashSet<RateUser>();
            this.RateUsers1 = new HashSet<RateUser>();
        }
        [Required(ErrorMessage = "Username is requried!")]
        [MaxLength(16, ErrorMessage = "Username must not exceed 16 characters")]
        [Display(Name = "Useename")]
        public string user_id { get; set; }
        public int permission_id { get; set; }
        [Required(ErrorMessage = "You must input password!")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [RegularExpression(@"(?=.*\d)(?=.*[A-Z]).(?=.*[a-z]).{6,16}", ErrorMessage = "Your password must be at least 6 characters long and contain at least 1 Lowercase letter, 1 Uppercase and 1 Number")] 
        public string password { get; set; }
        [NotMapped]
        [Display(Name = "Confirm your password")]
        [DataType(DataType.Password)]
        public string ConfirmPass { get; set; }
        [Required(ErrorMessage = "You must input phone number!")]
        [StringLength(10, MinimumLength = 10, ErrorMessage = "Must be 10 characters long.")]
        [Display(Name = "Phone")]
        [DataType(DataType.PhoneNumber)]
        public string phone { get; set; }
        [Display(Name = "Image")]
        public string image { get; set; }
        [Required(ErrorMessage = "You must input your email!")]
        [DataType(DataType.EmailAddress, ErrorMessage = "You must input your email!")]
        [Display(Name = "Email")]
        public string email { get; set; }
        public double rate { get; set; }
        public int rate_count { get; set; }
        public System.DateTime date_join { get; set; }
        public string Token { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dealed> Dealeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Follow> Follows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Follow> Follows1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications1 { get; set; }
        public virtual Permission Permission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RateUser> RateUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RateUser> RateUsers1 { get; set; }
    }
}
